
# Sunspot looks for environment variable SOLR_URL, so to avoid
# confusion, we use that instead of storing the Solr hostname, port,
# and path here.

production:
  solr:
    # hostname: localhost
    port: 8983
    log_level: WARNING
    # path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    log_level: INFO

staging:
  solr:
    log_level: INFO

test:
  solr:
    log_level: WARNING
