include:
  - project: "devops/gitlab/ci-templates/docker"
    ref: "master"
    file:
      - ".build_docker_image.yml"
      - ".push_docker_image.yml"
      - ".remove_docker_image.yml"
  - project: "devops/gitlab/ci-templates/sast"
    ref: "master"
    file:
      - ".trivy_container_scanning.yml"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED

stages:
  - sast:project
  - build:web
  - push:web
  - remove:web

build_web_image:
  stage: build:web
  extends:
    - .build_docker_image
  variables:
    CI_IMAGE_NAME: "${CI_PROJECT_ID}-${CI_PIPELINE_ID}-web"
  tags:
    - build

trivy_web_container_scanning:
  stage: sast:web
  extends:
    - .trivy_container_scanning
  needs:
    - build_web_image
  variables:
    CI_IMAGE_NAME: "${CI_PROJECT_ID}-${CI_PIPELINE_ID}-web"
  tags:
    - build
  allow_failure: true

push_web_image_to_registry:
  stage: push:web
  extends:
    - .push_docker_image
  needs:
    - trivy_web_container_scanning
  variables:
    CI_IMAGE_NAME: "${CI_PROJECT_ID}-${CI_PIPELINE_ID}-web"
    DOCKER_IMAGE_NAME: "sdbmss_web"
  tags:
    - build

remove_web_image:
  stage: remove:web
  extends:
    - .remove_docker_image
  needs:
    - push_web_image_to_registry
  variables:
    CI_IMAGE_NAME: "${CI_PROJECT_ID}-${CI_PIPELINE_ID}-web"
  rules:
    - when: always
  tags:
    - build
