name: sdbmss
env_file:
  - .lando.env
services:
  rabbitmq:
    type: compose
    portforward: 5672
    services:
      image: rabbitmq:3.7
      ports:
        - 5672:5672
      hostname: 'rabbitmq'
      command: rabbitmq-server
    overrides:
      volumes:
        - rabbitmq_data:/var/lib/rabbitmq
  jena:
    type: compose
    portforward: 3030
    services:
#      image: 'quay.io/upennlibraries/sdbm_jena:development'
      image: jena
      build:
        context: sdbmss_jena
        dockerfile: Dockerfile
      ports:
        - 3030:3030
      volumes:
        - rdf_data:/fuseki
      command: /docker-entrypoint.sh /jena-fuseki/start_jena.sh
  interface:
    type: compose
    services:
      image: 'quay.io/upennlibraries/sdbmss_interface:development'
      command: ruby interface.rb
  db:
    type: mysql:5.7
    portforward: 3307
  solr:
    type: compose
    portforward: true
    services:
      image: sdbmss
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8982:8982
      command: bundle exec rake sunspot:solr:run
  delayedjob:
    type: compose
    portforward: true
    services:
      image: sdbmss
      build:
        context: .
        dockerfile: Dockerfile
      command: bundle exec rake jobs:work
tooling:
  mysql:
    service: db
  rabbitmq:
    service: rabbitmq
proxy:
  solr:
    - sdbm.solr.lndo.site:8982
  rabbitmq:
    - sdbm.rabbitmq.lndo.site
  jena:
    - sdbm.jena.lndo.site:3030