name: sdbmss
env_file:
  - docker.env
services:
  rabbitmq:
    type: compose
    portforward: 5672
    services:
      image: rabbitmq:3.7
      ports:
        - 5672:5672
      hostname: 'rabbitmq'
      command: rabbitmq-server
  jena:
    type: compose
    portforward: 3030
    services:
      image: 'quay.io/upennlibraries/sdbm_jena:development'
      ports:
        - 3030:3030
      volumes:
        - rdf_data:/fuseki
      command:
        - rm /fuseki/system/tdb.lock
        - rm /fuseki/databases/sdbm/tdb.lock
        - cd /jena-fuseki
        - ./fuseki-server
  interface:
    type: compose
    services:
      image: 'quay.io/upennlibraries/sdbmss_interface:development'
      command: ruby interface.rb
  db:
    type: mysql:5.7
    portforward: true
    creds:
      user: sdbm
      password: sdbm
      database: sdbm
  solr:
    type: compose
    portforward: true
    services:
      image: sdbmss
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - 8982:8982
      command:
        - bundle exe rake sunspot:solr:start
  delayedjob:
    type: compose
    portforward: true
    services:
      image: sdbmss
      build:
        context: .
        dockerfile: Dockerfile
      command:
        - bundle exe rake jobs:work
