version: '2.2'

services:
  rabbitmq:
    image: rabbitmq:3
    env_file: .docker-environment
    hostname: 'rabbitmq'
    ports:
      - '5672:5672'
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret cookie here' # needed for rabbitmqctl to work (??)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    cpu_shares: 20
    logging:
      driver: "json-file"
    mem_limit: 3700m
    mem_reservation: 2000m      
    restart: always
  db:
    image: mysql/mysql-server:5.7
    env_file: .docker-environment
    cpu_shares: 80
    logging:
      driver: "json-file"
    ports:
      - "3307:3307"
    volumes:
      - sdbm_data:/var/lib/mysql
    restart: always
  solr:
    image: sdbm:latest
    ports:
      - "8982:8982"
    env_file: .docker-environment
    cpu_shares: 80
    logging:
      driver: "json-file"
    links:
      - db
    volumes:
      - sdbm_solr:/usr/src/app/solr
    command: bundle exec rake sunspot:solr:run
    restart: always
  rails:
    image: sdbm:latest
    env_file: .docker-environment
    cpu_shares: 80
    logging:
      driver: "json-file"
    restart: always
    links:
      - db
      - solr
      - rabbitmq
    depends_on:
      - "rabbitmq"
    volumes:
      - .:/usr/src/app
      - sdbm_assets:/usr/src/app/public/assets
      - sdbm_docs:/usr/src/app/public/static
  delayedjob:
    image: sdbm:latest
    depends_on:
      - "db"
      - "rabbitmq"
    links:
      - db
      - solr
    volumes:
      - .:/usr/src/app
    env_file: .docker-environment
    command: bundle exec rake jobs:work
    restart: always
    logging:
      driver: "json-file"
  jena:
    build: ./jena
    logging:
      driver: "json-file"
    volumes:
      - rdf_data:/fuseki
    mem_limit: 3700m
    mem_reservation: 2000m
    cpu_shares: 20
    env_file: .docker-environment
    restart: always
#      - JVM_ARGS=-Xmx3g   # raises memory limits to allow large file to be uploaded
  interface:
    build: ./interface
    command: ruby interface.rb
    env_file: .docker-environment
    cpu_shares: 20
    logging:
      driver: "json-file"
    links:
      - jena
      - rabbitmq
    depends_on:
      - "rabbitmq"
    mem_limit: 3700m
    mem_reservation: 2000m
    cpu_shares: 20
    env_file: .docker-environment
    restart: always
  nginx:
    build: ./nginx
    cpu_shares: 50
    volumes:
       - ${PWD}/docker/ssl:/etc/httpd/ssl
    logging:
      driver: "json-file"
    links:
      - rails
      - jena
    ports:
      - "80:80"
      - "443:443"
    restart: always
volumes:
  sdbm_docs:
  sdbm_data:
  rdf_data:
  sdbm_assets:
  sdbm_solr:
  rabbitmq_data:
