db:
  image: mysql/mysql-server:5.7
  env_file: .docker-environment
  ports:
    - "3307:3307"
  volumes:
    #- my.cnf:/etc/my.cnf --> user ENV variables to setup mysql db instead
    - docker_data:/var/lib/mysql
solr:
  build: .
  ports:
    - "8983:8983"
  env_file: .docker-environment
  links:
    - db
  volumes:
    - .:/usr/src/app
  command: bundle exec rake sunspot:solr:run

rails:
  build: .
  env_file: .docker-environment
  ports:
    - "8080:3000"
  links:
    - db
    - solr
  volumes:
    - .:/usr/src/app  
delayedjob:
  build: .
  links:
    - db
    - solr
  volumes:
    - .:/usr/src/app
  env_file: .docker-environment
  command: bundle exec rake jobs:work