version: '2'

services:
  rabbitmq:
    image: rabbitmq:3
    hostname: 'rabbitmq'
    ports:
      - '5672:5672'
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret cookie here' # needed for rabbitmqctl to work
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  db:
    image: mysql/mysql-server:5.7
    env_file: .docker-environment
    ports:
      - "3307:3307"
    volumes:
      - sdbm_data:/var/lib/mysql
  solr:
    image: sdbm:latest
    ports:
      - "8983:8983"
    env_file: .docker-environment
    links:
      - db
    volumes:
      - .:/usr/src/app
    command: bundle exec rake sunspot:solr:run

  rails:
    image: sdbm:latest
    env_file: .docker-environment
    ports:
      - "3000:3000"
    expose:
      - "3000"
    links:
      - db
      - solr
      - rabbitmq
    volumes:
      - .:/usr/src/app
  delayedjob:
    image: sdbm:latest
    depends_on:
      - "db"
    links:
      - db
      - solr
    volumes:
      - .:/usr/src/app
    env_file: .docker-environment
    command: bundle exec rake jobs:work
  jena:
    build: ./jena
    ports:
      - "3030:3030"
    volumes:
      - rdf_data:/fuseki
    expose:
      - "3030"
    environment:
      - ADMIN_PASSWORD="pw"    
      - JVM_ARGS=-Xmx3g   # raises memory limits to allow large file to be uploaded
      - VIRTUAL_HOST=jena.localhost.com
  interface:
    build: ./jena
    command: ruby interface.rb
    links:
      - jena
      - rabbitmq
    depends_on:
      - "rabbitmq"
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
volumes:
  sdbm_data:
  rdf_data:
  rabbitmq_data: