version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3
    hostname: 'rabbitmq'
    ports:
      - '5672:5672'
    environment:
      - RABBITMQ_ERLANG_COOKIE='secret cookie here' # needed for rabbitmqctl to work (??)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    logging:
      # driver: "journald"
  db:
    image: mysql/mysql-server:5.7
    # env_file: .docker-environment
    logging:
      # driver: "journald"
    ports:
      - "3307:3307"
    volumes:
      - sdbm_data:/var/lib/mysql
    environment:
      ADMIN_PASSWORD:
      RAILS_USER:
      RAILS_PASS:
      MYSQL_HOST:
      MYSQL_DATABASE:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
      RABBIT_PASSWORD:
      RABBIT_USER:
      SDBMSS_APP_HOST:
      SDBMSS_SMTP_HOST:
      SDBMSS_EMAIL_FROM:
      SDBMSS_NOTIFY_EMAIL:
      SDBMSS_NOTIFY_EMAIL_PASSWORD:
      SDBMSS_EMAIL_EXCEPTIONS_TO:
      SDBMSS_BLACKLIGHT_SECRET_KEY:
      SDBMSS_DEVISE_SECRET_KEY:
      SDBMSS_SECRET_KEY_BASE:
      SDBMSS_SECRET_TOKEN:
      SOLR_URL:
  solr:
    image: sdbm:latest
    ports:
      - "8982:8982"
    # env_file: .docker-environment
    logging:
      # driver: "journald"
    links:
      - db
    volumes:
      - sdbm_solr:/usr/src/app/solr
    command: bundle exec rake sunspot:solr:run
    environment:
      ADMIN_PASSWORD:
      RAILS_USER:
      RAILS_PASS:
      MYSQL_HOST:
      MYSQL_DATABASE:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
      RABBIT_PASSWORD:
      RABBIT_USER:
      SDBMSS_APP_HOST:
      SDBMSS_SMTP_HOST:
      SDBMSS_EMAIL_FROM:
      SDBMSS_NOTIFY_EMAIL:
      SDBMSS_NOTIFY_EMAIL_PASSWORD:
      SDBMSS_EMAIL_EXCEPTIONS_TO:
      SDBMSS_BLACKLIGHT_SECRET_KEY:
      SDBMSS_DEVISE_SECRET_KEY:
      SDBMSS_SECRET_KEY_BASE:
      SDBMSS_SECRET_TOKEN:
      SOLR_URL:
  rails:
    image: sdbm:latest
    # env_file: .docker-environment
    environment:
      ADMIN_PASSWORD:
      RAILS_USER:
      RAILS_PASS:
      MYSQL_HOST:
      MYSQL_DATABASE:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
      RABBIT_PASSWORD:
      RABBIT_USER:
      SDBMSS_APP_HOST:
      SDBMSS_SMTP_HOST:
      SDBMSS_EMAIL_FROM:
      SDBMSS_NOTIFY_EMAIL:
      SDBMSS_NOTIFY_EMAIL_PASSWORD:
      SDBMSS_EMAIL_EXCEPTIONS_TO:
      SDBMSS_BLACKLIGHT_SECRET_KEY:
      SDBMSS_DEVISE_SECRET_KEY:
      SDBMSS_SECRET_KEY_BASE:
      SDBMSS_SECRET_TOKEN:
      SOLR_URL:
    logging:
      # driver: "journald"
    links:
      - db
      - solr
      - rabbitmq
    depends_on:
      - "rabbitmq"
    volumes:
      - .:/usr/src/app
      - sdbm_assets:/usr/src/app/public/assets
      - sdbm_docs:/usr/src/app/public/static
  delayedjob:
    image: sdbm:latest
    depends_on:
      - "db"
      - "rabbitmq"
    links:
      - db
      - solr
    volumes:
      - .:/usr/src/app
    # env_file: .docker-environment
    environment:
      ADMIN_PASSWORD:
      RAILS_USER:
      RAILS_PASS:
      MYSQL_HOST:
      MYSQL_DATABASE:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
      RABBIT_PASSWORD:
      RABBIT_USER:
      SDBMSS_APP_HOST:
      SDBMSS_SMTP_HOST:
      SDBMSS_EMAIL_FROM:
      SDBMSS_NOTIFY_EMAIL:
      SDBMSS_NOTIFY_EMAIL_PASSWORD:
      SDBMSS_EMAIL_EXCEPTIONS_TO:
      SDBMSS_BLACKLIGHT_SECRET_KEY:
      SDBMSS_DEVISE_SECRET_KEY:
      SDBMSS_SECRET_KEY_BASE:
      SDBMSS_SECRET_TOKEN:
      SOLR_URL:
    command: bundle exec rake jobs:work
    logging:
      # driver: "journald"
  jena:
    image: 'jena_sdbm:latest'
    logging:
      # driver: "journald"
    ports:
      - "3030:3030"
    volumes:
      - rdf_data:/fuseki
    # env_file: .docker-environment
    environment:
      ADMIN_PASSWORD:
      RAILS_USER:
      RAILS_PASS:
      MYSQL_HOST:
      MYSQL_DATABASE:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
      RABBIT_PASSWORD:
      RABBIT_USER:
      SDBMSS_APP_HOST:
      SDBMSS_SMTP_HOST:
      SDBMSS_EMAIL_FROM:
      SDBMSS_NOTIFY_EMAIL:
      SDBMSS_NOTIFY_EMAIL_PASSWORD:
      SDBMSS_EMAIL_EXCEPTIONS_TO:
      SDBMSS_BLACKLIGHT_SECRET_KEY:
      SDBMSS_DEVISE_SECRET_KEY:
      SDBMSS_SECRET_KEY_BASE:
      SDBMSS_SECRET_TOKEN:
      SOLR_URL:
  interface:
    image: 'interface:latest'
    command: ruby interface.rb
    logging:
      # driver: "journald"
    links:
      - jena
      - rabbitmq
    depends_on:
      - "rabbitmq"
    # env_file: .docker-environment
    environment:
      ADMIN_PASSWORD:
      RAILS_USER:
      RAILS_PASS:
      MYSQL_HOST:
      MYSQL_DATABASE:
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER:
      MYSQL_PASSWORD:
      RABBIT_PASSWORD:
      RABBIT_USER:
      SDBMSS_APP_HOST:
      SDBMSS_SMTP_HOST:
      SDBMSS_EMAIL_FROM:
      SDBMSS_NOTIFY_EMAIL:
      SDBMSS_NOTIFY_EMAIL_PASSWORD:
      SDBMSS_EMAIL_EXCEPTIONS_TO:
      SDBMSS_BLACKLIGHT_SECRET_KEY:
      SDBMSS_DEVISE_SECRET_KEY:
      SDBMSS_SECRET_KEY_BASE:
      SDBMSS_SECRET_TOKEN:
      SOLR_URL:
  nginx:
    image: 'nginx_sdbm:latest'
    volumes:
      - /etc/httpd/ssl:/etc/httpd/ssl
    logging:
      # driver: "journald"
    links:
      - rails
      - jena
    ports:
      - "80:80"
      - "443:443"
volumes:
  sdbm_docs:
  sdbm_data:
  rdf_data:
  sdbm_assets:
  sdbm_solr:
  rabbitmq_data:
