---
is_development: false
project_root: "/opt/devops"

cronjobs:
  - name: "Cleanup Sessions"
    minute: "0"
    hour: "1"
    day: "*"
    weekday: "*"
    job: "/bin/bash -l -c 'docker exec -t $(docker ps -q -f name=sdbmss_rails) /bin/bash cleanup_sessions.sh'"
  - name: "Daily db backup"
    minute: "0"
    hour: "1"
    day: "*"
    weekday: "*"
    job: "/bin/bash -l -c 'docker exec -t $(docker ps -q -f name=sdbmss_rails) /bin/bash backup_db.sh && docker cp $(docker ps -q -f name=sdbmss_rails):/tmp/sdbm.sql.gz /home/LIBRARY/emeryr/sdbmss/backup/sdbm.sql.gz'"
  - name: "Weekly db backup"
    minute: "0"
    hour: "1"
    day: "*"
    weekday: "0"
    job: "/bin/bash -l -c 'docker exec -t $(docker ps -q -f name=sdbmss_rails) /bin/bash backup_db.sh && docker cp $(docker ps -q -f name=sdbmss_rails):/tmp/sdbm.sql.gz /home/LIBRARY/emeryr/sdbmss/backup/sdbm-weekly.sql.gz'"
  - name: "Monthly db backup"
    minute: "0"
    hour: "1"
    day: "1"
    weekday: "*"
    job: "/bin/bash -l -c 'docker exec -t $(docker ps -q -f name=sdbmss_rails) /bin/bash backup_db.sh && docker cp $(docker ps -q -f name=sdbmss_rails):/tmp/sdbm.sql.gz /home/LIBRARY/emeryr/sdbmss/backup/sdbm-monthly.sql.gz'"
  - name: "getrdf"
    minute: "0"
    hour: "1"
    day: "*"
    weekday: "*"
    job: "/bin/bash -l -c 'docker exec -t $(docker ps -q -f name=sdbmss_rails) /bin/bash getrdf.sh'"
  - name: "jena:verify"
    minute: "0"
    hour: "1"
    day: "*"
    weekday: "*"
    job: "/bin/bash -l -c 'docker exec -t $(docker ps -q -f name=sdbmss_rails) bundle exec rake jena:verify'"
  - name: "do_csv_dump"
    minute: "0"
    hour: "1"
    day: "*"
    weekday: "*"
    job: "/bin/bash -l -c 'docker exec -t $(docker ps -q -f name=sdbmss_rails) bundle exec rails runner \"Entry.do_csv_dump\"'"
