source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2.11.3'

gem 'actionview', '~> 4.2.11.3'
gem 'actionview-encoded_mail_to'
gem 'activejob', '~> 4.2.11.3'
gem 'activerecord-session_store', '~> 0.1.0'
gem 'autoprefixer-rails' #, '~> 7.1.6'
gem 'bigdecimal', '1.3.5'
gem 'blacklight', '~> 5.14.0'
gem 'blacklight_advanced_search', '5.1.3'
gem 'bunny'
gem 'cancancan', '~> 1.12.0'
gem 'chronic', '~> 0.10.2'
gem 'codemirror-rails'
gem 'coffee-rails', '~> 4.0.0'
gem 'daemons', '~> 1.2.2'
gem 'data-confirm-modal'
gem 'database_cleaner', '~> 1.4.1'
gem 'date', '~> 2.0'
gem 'delayed_job'
gem 'delayed_job_active_record'
gem 'devise', '~> 4.7.1'
gem 'devise-guests', '~> 0.3.0'
gem 'exception_notification', '~> 4.1.1'
gem 'ffi', '1.14.0'
gem 'god', '~> 0.13.6'
gem 'html-pipeline', '~> 2.12.3'
gem 'invisible_captcha', '< 2.0'
gem 'jbuilder', '~> 2.2.0'
gem 'jettywrapper', '~> 2.0.3'
gem 'jquery-rails', '~> 4.2.1'
gem 'jquery-ui-rails', '~> 5.0.3'
gem 'kramdown', '<= 1.16.2'
gem 'levenshtein', '~> 0.2.2'
gem 'logger', '~> 1.2.7'
gem 'mysql2'
gem 'mysql2'
gem 'net-ssh', '< 5.0'
gem 'nokogiri', '~> 1.13.10'
gem 'number_to', '~> 0.7.1'
gem 'paper_trail', '~> 4.0.0'
gem 'rack', '~> 1.3'
gem 'rack-handlers'
gem 'rake', '10.5.0'
gem 'rubyzip', '~> 1.0'
gem 'sass-rails', '~> 5.0.3'
gem 'sassc' #, '<= 1.12.1'
gem 'sprockets', '>= 3.7.2'
gem 'sunspot_rails', '2.2.0' # updating sunspot beyond 2.2.0 causes SOLR nullPointerException errors...
gem 'sunspot_solr', '2.2.0'
gem 'thredded', '~> 0.9.4'
gem 'timeout', '0.4.4'
gem 'turbolinks', '~> 2.5.0'
gem 'turnout', '~> 2.1.0'
gem 'uglifier', '~> 2.7.2'
# gem 'unicorn', '~> 4.9.0'
gem 'unicorn-rails'
gem 'websocket-driver', '~> 0.7.7'
gem 'whenever', :require => false

# bundle exec rake doc:rails generates the Rails API under doc/api.
group :doc do
  gem 'sdoc', '~> 0.4.0'
  gem 'yard', '~> 0.9.11'
end

group :development do
  # in-browser console
  gem 'web-console', '~> 2.1'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '~> 1.1.0'
  # Use Capistrano for deployment
  gem 'capistrano-rails', '~> 1.1.0'
  gem 'pry-rails'

  # This can autogenerate ERD diagrams from ActiveRecord models and
  # schema. This causes problems when it's enabled for anything
  # besides running 'bundle exec erd' (but I can't remember exactly
  # what the probs were) which is why it's commented out.
  # gem 'rails-erd', require: false, group: :development
end

group :test, :development do
  gem 'rspec-rails', '~> 3.1.0'
  gem 'cuprite', '0.13'
  gem 'capybara', '~> 2.7.1'
  gem 'capybara-screenshot'
  gem 'factory_girl_rails', '~> 4.0'
  gem 'poltergeist', '~> 1.6.0'
  gem 'simplecov', :require => false
end