source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.2.8'

gem "nokogiri", "< 1.16"
# gem "loofah", "= 2.19.1" # updated to 2.21.1, but that calls for Nokogiri::HTML4, which is not available in 1.8.5
gem "rubyzip", "~> 2.3"
gem "ffi", ">= 1.9.24", "< 1.17"
gem "json", ">= 2.3"
gem "psych", "~> 3.1"
gem "rdoc", "~> 6.3.0"
gem "sprockets", ">= 3.7.2"
gem "kramdown"
gem "sassc", ">= 2.0.0"
gem 'autoprefixer-rails', '~> 7.1.6'
gem 'html-pipeline', '~> 2.12.3'
gem 'websocket-driver', '~> 0.7.7'

gem 'invisible_captcha'

gem 'actionview-encoded_mail_to'

gem 'mysql2'
gem 'bigdecimal'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '~> 2.7.2'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.2'

# Use jquery as the JavaScript library
gem 'jquery-rails', '~> 4.2.1'
gem 'jquery-ui-rails', '~> 5.0.3'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks', '~> 5.2'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.11.0'

# Use unicorn as the app server
gem 'unicorn', '~> 4.9.0'
gem 'unicorn-rails'
gem 'rack-handlers'

# Blacklight
gem "blacklight", "~> 6.25"
gem "twitter-typeahead-rails", "= 0.11.1.pre.corejavascript"
gem "rsolr", "~> 2.0"
gem "blacklight_advanced_search", "~> 6.4.1"

# For authentication; used by Blacklight and by SDBMSS
gem "devise", "~> 4.7.1"
gem "devise-guests", "~> 0.3.0"

# Extracted from Rails 5; needed by Blacklight
gem "responders", "~> 3.0"

# For roles and permissions checking
gem "cancancan", "~> 3.5"

# For indexing records in Solr
gem 'sunspot_rails', '~> 2.5.0'

# Use database as session store
gem 'activerecord-session_store', '~> 1.1'

# for calculating string similarity
gem 'levenshtein', '~> 0.2.2'

# for auditing model changes
gem 'paper_trail', '~> 10.3'

# natural language date parser
gem 'chronic', '~> 0.10.2'

# async background job processing
gem 'delayed_job', '~> 4.1.0'
gem 'delayed_job_active_record'

# neeeded for delayed_job script to run in background
gem "daemons", '~> 1.2.2'

# manage and monitor application processes
gem "god", "~> 0.13.6"

# ability to put entire app in maintenance mode
# turnout ~> 2.1.0 requires rack ~> 1.3, incompatible with Rails 5.2 (Rack 2.x)
# TODO: find a Rack 2-compatible replacement or fork
# gem "turnout", "~> 2.1.0"

# send email notifications on app exceptions
gem "exception_notification", "~> 4.5"

# converts fixnums to string equivalents
gem "number_to", "~> 0.7.1"

# empties db after each group of tests
gem "database_cleaner", "~> 2.0"

# for compressing csv exports to .zip
# gem "rubyzip"

#gem "linkeddata"
#gem "rdf-turtle"
gem "bunny", "~> 2.22"

gem 'data-confirm-modal'

gem 'thredded', '~> 0.16'

gem 'whenever', :require => false

gem 'codemirror-rails'

# bundle exec rake doc:rails generates the Rails API under doc/api.
group :doc do
  gem 'sdoc', '~> 1.1'
  gem 'yard', '~> 0.9.11'
end

group :development do
  # in-browser console
  gem 'web-console', '~> 3.7'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '~> 2.1'
  # Use Capistrano for deployment
  gem 'capistrano-rails', '~> 1.1.0'
  gem 'pry-rails'
  # Intercept outgoing mail in development; view at /letter_opener
  gem 'letter_opener_web'

  # This can autogenerate ERD diagrams from ActiveRecord models and
  # schema. This causes problems when it's enabled for anything
  # besides running "bundle exec erd" (but I can't remember exactly
  # what the probs were) which is why it's commented out.
  # gem 'rails-erd', require: false, group: :development
end

group :test, :development do
  gem 'puma'
  gem 'rspec-rails', '~> 5.0'
  gem 'capybara', '~> 3.35', '< 3.40'
  gem 'capybara-screenshot'
  gem "factory_bot_rails", "~> 5.2"
  gem 'cuprite'
  gem 'debug'
  gem 'simplecov', :require => false
  gem 'stackprof', '>= 0.2.9', require: false
  gem 'test-prof'
  gem 'byebug', '< 12'
end
