
# TODO: figure out a way to pull this configuration from environment
# variables; right now, it duplicates SDBMSS_SOLR_URL

production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/development

staging:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/test
