---
solr_collections:
  - name: sdbm-development
    configset: sdbm
    replicas: 1
    shards: 1

solr_configsets:
  - name: "sdbm"
    path: "roles/app/files/src/solr/conf/"

solr_docker_image_tag: 9.3.0

solr_proxy_host: "sdbm-dev.library.upenn.int"

solr_instances: 1

solr_collection_replicas: 1

solr_custom_env_variables:
  SOLR_ENABLE_AUTHENTICATION: "yes"
  SOLR_ADMIN_USERNAME: "admin"
  SOLR_ADMIN_PASSWORD: "password"
