---
- name: Create symlink
  ansible.builtin.file:
    src: "../../../../rails_app"
    dest: "{{ role_path + '/files/src' }}"
    state: link
    force: true
  when: is_development | default (false, true)
  tags: dev_environment
