---
- name: "Debug - Output docker-compose.yml object"
  ansible.builtin.debug:
    msg: "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"
  when: solr_debug | default (false, true)
  tags:
    - debug

- name: "Deploy solr"
  community.docker.docker_stack:
    name: "sdbmss"
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2') | from_yaml }}"
    state: present
